name: Machine Learning Workflow CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
    # 1. Mengambil kode dari repositori GitHub
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Menyiapkan runtime Python di GitHub Virtual Machine
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # 3. Melakukan autentikasi masuk ke Docker Hub menggunakan GitHub Secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 4. Membangun Docker Image menggunakan Dockerfile standar (Solusi Eror)
    - name: Build Docker Image
      run: |
        cd MLProject
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-flower-model:latest .

    # 5. Mengunggah Image hasil build ke cloud Docker Hub
    - name: Push Docker Image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-flower-model:latest